site_name: Orbiter
repo_url: https://github.com/astronomer/orbiter
edit_uri: edit/main/docs/
site_url: https://astronomer.github.io/orbiter/

theme:
    name: material
    logo: orbiter.svg
    favicon: orbiter.png

    palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    font:
      text: Roboto
      code: Roboto Mono

    features:
      - navigation.path
#      - navigation.sections  #
#      - navigation.tabs
#      - navigation.tabs.sticky
#      - navigation.top
      - navigation.instant
      - navigation.instant.progress
      - navigation.tracking
#      - navigation.indexes #
      - navigation.expand #
      - toc.follow
      - toc.integrate  #
      - content.tabs.link
      - content.action.edit
      - content.code.copy
      - content.code.annotate
      - search.share
      - search.highlight
      - search.suggest

extra_css:
- style.css

markdown_extensions:
# Auto-documents click
- mkdocs-click

- toc:
    permalink: true

- pymdownx.superfences:
    # Mermaid Diagrams
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

# Snippets provides the -8<-- syntax https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
- pymdownx.snippets

# https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
- pymdownx.magiclink
- pymdownx.saneheaders

- pymdownx.highlight:
    use_pygments: true
    anchor_linenums: true
- pymdownx.inlinehilite

- admonition
- pymdownx.details


plugins:
- search
- markdown-exec  # for rendering the csv table of origins to share w/ CLI
- autorefs
- mkdocstrings:
    custom_templates: docs/templates
    handlers:
      python:
        options:
          docstring_style: sphinx
          show_source: true
          show_root_heading: true
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true
          unwrap_annotated: true
          show_object_full_path: false
          show_symbol_type_toc: true
          merge_init_into_class: true
          parameter_headings: true
          summary: true
          group_by_category: true
          docstring_options:
            trim_doctest_flags: true
          show_bases: false
          extensions:
          - griffe_inherited_docstrings

copyright: "Apache Airflow® is a trademark of the Apache Software Foundation. Copyright 2024 Astronomer, Inc."
